### ISSUE TITLE
Error trying to equate

### ISSUE THREAD

**Issue by frankbach** [dexter-psychometrics/dexter#11]
I have tried to exclude missing values when equating as follows
```{r echo=FALSE, message=FALSE, warning=FALSE}
p_sm <- fit_enorm(gbpnas, response != -99, method = "CML")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
ref_items <- get_design(gbpnas) |> 
    filter(booklet_id == "h22") |> select(item_id) |> as_vector()
target_booklet <- tibble(booklet_id="h23", item_id = get_design(gbpnas) |> 
                           select(item_id) |> as_vector())
ou_e <- probability_to_pass(gbpnas, p_sm,
    ref_items = ref_items,
    target_booklets = target_booklet,
    pass_fail = 124)
```
But when I run the last part above R crashes and I have to restart. Any suggestions?

Best regards
Frank

**Comment by jessekps** [comment]
No, at that is a bug. Which version of dexte rare you using? And is there any chance you could share this dataset? If the dataset is confidential, then the output of `design_info(gbpnas, response != -99)$design` would also be helpful (that would contain booklet id's, item id's, the design and number of persons per booklet but no responses or other identifying information). You can email it to jesse.koops at cito.nl.

**Comment by jessekps** [comment]
Hi Frank,

I could not replicate the problem nor find any points in the code that could conceivably crash an R session. Nevertheless, I updated the function so I'm curious if the problem persists before I delve deeper.

Could you try installing the development version and try your code again?

`remotes::install_github("dexter-psychometrics/dexter")`

**Comment by jessekps** [comment]
Ah, I guess you're on a Mac. Installation from source is tricky on a Mac. I'll have to think about it.

**Comment by jessekps** [comment]
If you're on a Mac, you can try to follow the instructions here:
https://github.com/dexter-psychometrics/dexterMML/blob/master/dexterMML%20setup%20on%20macOS.md

And then, in the final part instead of where it says "Install dexterMML" you can run: 
`remotes::install_github("dexter-psychometrics/dexter")`

I don't know how difficult it will be since I don't have access to a Mac.

**Comment by frankbach** [comment]
I have tried to follow the instruction, but I got the following message.

elsym.cpp:3:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
make: *** [elsym.o] Error 1
ERROR: compilation failed for package ‘dexter’
* removing ‘/Users/xbacfr/Documents/Forskning/RPackages/dexter’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/fw/1hmtlxpn6bj9_g8szjkbdj7c0000gp/T//RtmpmpW1m4/file759a70780403/dexter_1.3.0.tar.gz’ had non-zero exit status

One thing was not clear to me, where to put the .R/Makevars. I have tried a couple of different locations, but none of them worked.

Best,

Frank

24 nov. 2023 kl. 15:01 skrev Jesse Koops ***@***.***>:



If you're on a Mac, you can try to follow the instructions here:
https://github.com/dexter-psychometrics/dexterMML/blob/master/dexterMML%20setup%20on%20macOS.md

And then, in the final part instead of where it says "Install dexterMML" you can run:
remotes::install_github("dexter-psychometrics/dexter")

I don't know how difficult it will be since I don't have access to a Mac.

**Comment by jessekps** [comment]
Well, in theory the makeVars should be placed here: `file.path(normalizePath('~'),'.R')`, but that might not be the issue, R on a mac is tricky. I'll try to borrow a mac from someone in the office. This may take some time.

**Comment by frankbach** [comment]
Thanks for your efforts!

Frank

28 nov. 2023 kl. 08:20 skrev Jesse Koops ***@***.***>:



Well, in theory the makeVars should be placed here: file.path(normalizePath('~'),'.R'), but that might not be the issue, R on a mac is tricky. I'll try to borrow a mac from someone in the office. This may take some time.

**Comment by jessekps** [comment]
I've pushed a new version to github which should be installable on a mac by just using `remotes::install_github("dexter-psychometrics/dexter")`. And then I'd be curious if your original problem still persists.

**Comment by frankbach** [comment]
Thanx!
Hi Jesse! When I try to exclude the missing responses, it takes a very long time (an hour or more) and the the size of the object shrinks from 52 MB to around 4 MB. I think that all responsen on items where there are missing responses are removed. What would be a correct code to exlude missing responses from the data set when performing fit_enorm()?

**Comment by jessekps** [comment]
Assuming your missing_responses are coded -99, this would be correct. 
```
p_sm <- fit_enorm(gbpnas, response != -99, method = "CML")
```
Usually for educational tests missing responses are just scored 0 and in the item calibration persons with a too high percentage missing are removed or only 'not reached' responses are removed; then the code would be a little different.

An hour is very long, CML usually takes seconds. However, CML is a test form/booklet based method. If the number of missing responses is large it could become slow if you essentially create a separate booklet per person (since almost none of the persons would have the exact same missing pattern, each person would get a unique test form). You could check this by running:

```
dsg = design_info(gbpnas, response != -99)

n_distinct(dsg$design$booklet_id)
```
1000's of booklets might be problematic, especially on a mac where the computations are not done in parallel.  Such a dataset without a booklet design is not well suited for CML and you might switch to an MML package.
